semi: false
singleQuote: true
trailingComma: 'es5'
importOrder: ['^(components|utils|background|tests)/(.*)$', '^[./]']
importOrderSeparation: true
importOrderParserPlugins:
  [
    'jsx',
    'typescript',
    'classProperties',
    '["decorators", { "decoratorsBeforeExport": true }]',
  ]
