name: Release

on:
  push:
    tags:
      - '*'

env:
  APP_NAME: tabbed
  VERSION: 0.0.2

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    name: Build extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build-chrome

      - name: Rename and zip build output
        run: |-
          mv build ${{ env.APP_NAME }}-${{ env.VERSION }}
          zip -r ${{ env.APP_NAME }}-${{ env.VERSION }}-unpacked.zip ${{ env.APP_NAME }}-${{ env.VERSION }}

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}-${{ env.VERSION }}-unpacked
          path: ${{ env.APP_NAME }}-${{ env.VERSION }}-unpacked.zip

  release:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    name: Upload extension to releases
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Download unpacked artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-${{ env.VERSION }}-unpacked

      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: Upload packed extension to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.APP_NAME }}-${{ env.VERSION }}-unpacked.zip
          asset_name: ${{ env.APP_NAME }}-${{ env.VERSION }}-unpacked.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "${{ env.VERSION }}"
